name = "tc-status"
type = "webpack"
account_id = "28f1e029a998697424bf651aa210243f"
workers_dev = false
route = "status.tallcraft.com/*"
zone_id = "4f3170704efec21f70c6983de05161e0"

[site]
bucket = "dist"
entry-point = "workers-site"
